"""remove is_admin column

Revision ID: 08034ad96a4a
Revises: 5776f2aea8bb
Create Date: 2023-03-26 13:04:16.543546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08034ad96a4a'
down_revision = '5776f2aea8bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
